# Generated by Django 4.2.4 on 2023-08-13 19:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_about_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='about',
            field=ckeditor.fields.RichTextField(default='syllabus'),
        ),
    ]
