# Generated by Django 4.2.4 on 2023-08-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_alter_about_us_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
