# Generated by Django 4.2.4 on 2023-08-14 19:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0009_alter_hero_section_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('name_of_service', models.CharField(help_text='enter name of service', max_length=200)),
                ('about_service', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='about_us',
            name='about',
            field=ckeditor.fields.RichTextField(default='about us'),
        ),
        migrations.AlterField(
            model_name='hero_section',
            name='body',
            field=models.CharField(help_text='enter body', max_length=200),
        ),
        migrations.AlterField(
            model_name='hero_section',
            name='title',
            field=models.CharField(help_text='enter title', max_length=50),
        ),
    ]
