# Generated by Django 4.2.4 on 2023-08-14 20:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0010_services_alter_about_us_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='about_service',
            field=ckeditor.fields.RichTextField(default='about us'),
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=ckeditor.fields.RichTextField(default='about us'),
        ),
    ]
