# Generated by Django 4.2.4 on 2023-08-14 20:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0011_alter_services_about_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField(default='about service')),
            ],
        ),
        migrations.RemoveField(
            model_name='services',
            name='description',
        ),
    ]
