# Generated by Django 4.2.4 on 2023-08-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0012_mainservices_remove_services_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='team')),
                ('position', models.CharField(max_length=200)),
                ('about', models.CharField(max_length=300)),
                ('twitter', models.URLField(blank=True, help_text='Enter your Twitter profile link here.', null=True, verbose_name='Twitter Link')),
                ('facebook', models.URLField(blank=True, help_text='Enter your Twitter profile link here.', null=True, verbose_name='Facebook Link')),
                ('instagram', models.URLField(blank=True, help_text='Enter your Twitter profile link here.', null=True, verbose_name='Instagram Link')),
                ('linkedln', models.URLField(blank=True, help_text='Enter your Twitter profile link here.', null=True, verbose_name='Linkedln Link')),
            ],
        ),
    ]
