# Generated by Django 4.2.4 on 2023-08-14 22:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0014_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
