# Generated by Django 4.2.4 on 2023-08-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0017_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=700)),
                ('replied_status', models.CharField(blank=True, choices=[('r', 'replied'), ('n', 'new_message')], default='n', max_length=20, null=True)),
            ],
        ),
    ]
